# Generated by Django 6.0.2 on 2026-02-10 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_provozu', models.IntegerField(unique=True)),
                ('nazev', models.CharField(max_length=255)),
                ('ulice', models.CharField(blank=True, max_length=255)),
                ('mesto', models.CharField(blank=True, max_length=255)),
                ('kraj', models.CharField(blank=True, max_length=255)),
                ('psc', models.CharField(blank=True, max_length=20)),
                ('manazer', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Provoz',
                'verbose_name_plural': 'Provozy',
            },
        ),
        migrations.CreateModel(
            name='UzivatelskyProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HR', 'HR'), ('OBL', 'Oblastní manažer'), ('MAN', 'Manažer provozu')], default='MAN', max_length=3)),
                ('provozy', models.ManyToManyField(blank=True, related_name='uzivatele', to='provozy.provoz')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uživatelský profil',
                'verbose_name_plural': 'Uživatelské profily',
            },
        ),
    ]
