# Generated by Django 6.0.2 on 2026-02-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provozy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provoz',
            name='cislo_provozu',
            field=models.IntegerField(),
        ),
    ]
