# Generated by Django 6.0.2 on 2026-02-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provozy', '0002_alter_provoz_cislo_provozu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provoz',
            name='cislo_provozu',
            field=models.IntegerField(verbose_name='Číslo provozu'),
        ),
        migrations.AlterField(
            model_name='provoz',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E‑mail'),
        ),
        migrations.AlterField(
            model_name='provoz',
            name='kraj',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kraj'),
        ),
        migrations.AlterField(
            model_name='provoz',
            name='manazer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Manažer'),
        ),
        migrations.AlterField(
            model_name='provoz',
            name='mesto',
            field=models.CharField(blank=True, max_length=255, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='provoz',
            name='nazev',
            field=models.CharField(max_length=255, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='provoz',
            name='psc',
            field=models.CharField(blank=True, max_length=20, verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='provoz',
            name='ulice',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ulice'),
        ),
    ]
