# Generated by Django 6.0.2 on 2026-02-10 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provozy', '0003_alter_provoz_cislo_provozu_alter_provoz_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OsobniDotaznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titul', models.CharField(blank=True, max_length=50, verbose_name='Titul')),
                ('jmeno', models.CharField(max_length=100, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=100, verbose_name='Příjmení')),
                ('rodne_prijmeni', models.CharField(blank=True, max_length=200, verbose_name='Rodné a dřívější příjmení')),
                ('datum_narozeni', models.DateField(verbose_name='Datum narození')),
                ('misto_narozeni', models.CharField(max_length=200, verbose_name='Místo narození')),
                ('statni_obcanstvi', models.CharField(max_length=100, verbose_name='Státní občanství')),
                ('rodinny_stav', models.CharField(blank=True, max_length=100, verbose_name='Rodinný stav')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('rodne_cislo', models.CharField(max_length=20, verbose_name='Rodné číslo')),
                ('zdravotni_pojistovna', models.CharField(max_length=100, verbose_name='Zdravotní pojišťovna')),
                ('cislo_uctu', models.CharField(blank=True, max_length=50, verbose_name='Číslo účtu')),
                ('kod_banky', models.CharField(blank=True, max_length=10, verbose_name='Kód banky')),
                ('nazev_banky', models.CharField(blank=True, max_length=200, verbose_name='Název banky/spořitelny')),
                ('trv_ulice', models.CharField(max_length=200, verbose_name='Trvalé bydliště – ulice')),
                ('trv_cislo', models.CharField(max_length=50, verbose_name='Trvalé bydliště – číslo')),
                ('trv_mesto', models.CharField(max_length=200, verbose_name='Trvalé bydliště – město')),
                ('trv_psc', models.CharField(max_length=20, verbose_name='Trvalé bydliště – PSČ')),
                ('dor_ulice', models.CharField(blank=True, max_length=200, verbose_name='Doručovací adresa – ulice')),
                ('dor_cislo', models.CharField(blank=True, max_length=50, verbose_name='Doručovací adresa – číslo')),
                ('dor_mesto', models.CharField(blank=True, max_length=200, verbose_name='Doručovací adresa – město')),
                ('dor_psc', models.CharField(blank=True, max_length=20, verbose_name='Doručovací adresa – PSČ')),
                ('duchod_predcasny', models.BooleanField(default=False, verbose_name='Předčasný důchod')),
                ('duchod_starobni', models.BooleanField(default=False, verbose_name='Starobní důchod')),
                ('duchod_invalidni', models.BooleanField(default=False, verbose_name='Invalidní důchod')),
                ('duchod_datum_vzniku', models.DateField(blank=True, null=True, verbose_name='Datum vzniku nároku na důchod')),
                ('duchod_kdo_vyplaci', models.CharField(blank=True, max_length=200, verbose_name='Kdo důchod vyplácí')),
                ('vzdelani_zakladni', models.BooleanField(default=False, verbose_name='Základní škola')),
                ('vzdelani_sou', models.BooleanField(default=False, verbose_name='Střední odborné učiliště')),
                ('vzdelani_sou_rok_ukonceni', models.CharField(blank=True, max_length=10, verbose_name='SOÚ – rok ukončení')),
                ('vzdelani_ss', models.BooleanField(default=False, verbose_name='Střední škola')),
                ('vzdelani_ss_mesto', models.CharField(blank=True, max_length=100, verbose_name='Střední škola – město/obec')),
                ('vzdelani_gymnazium', models.BooleanField(default=False, verbose_name='Gymnázium')),
                ('vzdelani_gymnazium_skola', models.CharField(blank=True, max_length=150, verbose_name='Gymnázium – škola (název)')),
                ('vzdelani_vs', models.BooleanField(default=False, verbose_name='Vysoká škola')),
                ('vzdelani_vs_obor', models.CharField(blank=True, max_length=150, verbose_name='Vysoká škola – obor')),
                ('vzdelani_zakončeno_vyucni_list', models.BooleanField(default=False, verbose_name='Zakončeno – výuční list')),
                ('vzdelani_zakončeno_maturita', models.BooleanField(default=False, verbose_name='Zakončeno – maturitní vysvědčení')),
                ('vzdelani_zakončeno_diplom', models.BooleanField(default=False, verbose_name='Zakončeno – diplom')),
                ('posledni_zamestnavatel_nazev', models.CharField(blank=True, max_length=200, verbose_name='Poslední zaměstnavatel – název firmy')),
                ('posledni_zamestnavatel_pozice', models.CharField(blank=True, max_length=200, verbose_name='Poslední zaměstnavatel – pracovní zařazení')),
                ('posledni_zamestnavatel_od', models.DateField(blank=True, null=True, verbose_name='Poslední zaměstnavatel – od')),
                ('posledni_zamestnavatel_do', models.DateField(blank=True, null=True, verbose_name='Poslední zaměstnavatel – do')),
                ('pozice', models.CharField(max_length=150, verbose_name='Pozice')),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True)),
                ('datum_aktualizace', models.DateTimeField(auto_now=True)),
                ('provoz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dotazniky', to='provozy.provoz', verbose_name='Provoz')),
                ('vytvoril', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vytvorene_dotazniky', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
            ],
            options={
                'verbose_name': 'Osobní dotazník',
                'verbose_name_plural': 'Osobní dotazníky',
                'ordering': ['-datum_vytvoreni'],
            },
        ),
    ]
