# Generated by Django 6.0.2 on 2026-02-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pozice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=150, unique=True, verbose_name='Název pozice')),
                ('kod', models.CharField(help_text='Krátký kód (např. PPM_KUCHAR, PPM_MANAZER_PROVOZU apod.)', max_length=50, unique=True, verbose_name='Kód pozice')),
            ],
            options={
                'verbose_name': 'Pozice',
                'verbose_name_plural': 'Pozice',
                'ordering': ['nazev'],
            },
        ),
    ]
