# Generated by Django 6.0.2 on 2026-02-11 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0001_initial'),
        ('provozy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='osobnidotaznik',
            name='provoz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dotazniky', to='provozy.provoz', verbose_name='Provoz'),
        ),
        migrations.AddField(
            model_name='osobnidotaznik',
            name='vytvoril',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vytvorene_dotazniky', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil'),
        ),
        migrations.AddField(
            model_name='osobnidotaznik',
            name='pozice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dotazniky', to='onboarding.pozice', verbose_name='Pozice'),
        ),
    ]
