# Generated by Django 6.0.2 on 2026-02-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osobnidotaznik',
            name='nastup_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Datum nástupu do práce'),
        ),
        migrations.AddField(
            model_name='osobnidotaznik',
            name='pomer_do',
            field=models.DateField(blank=True, null=True, verbose_name='Pracovní poměr na dobu určitou do'),
        ),
        migrations.AddField(
            model_name='osobnidotaznik',
            name='rozvrzeni_pracovni_doby',
            field=models.CharField(choices=[('ROVNOMERNE', 'Rovnoměrné rozvržení pracovní doby'), ('NEROVNOMERNE', 'Nerovnoměrné rozvržení pracovní doby')], default='ROVNOMERNE', max_length=20, verbose_name='Rozvržení pracovní doby'),
        ),
        migrations.AddField(
            model_name='osobnidotaznik',
            name='tydenni_uvazek_hodin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Např. 40, 38.75, 37.5', max_digits=4, null=True, verbose_name='Týdenní pracovní doba v hodinách'),
        ),
        migrations.AddField(
            model_name='osobnidotaznik',
            name='typ_pomeru',
            field=models.CharField(choices=[('DOBA_NEURCITA', 'Pracovní poměr na dobu neurčitou'), ('DOBA_URCITA', 'Pracovní poměr na dobu určitou')], default='DOBA_NEURCITA', max_length=20, verbose_name='Typ pracovního poměru'),
        ),
        migrations.AddField(
            model_name='osobnidotaznik',
            name='zkusebni_doba_mesice',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Max. 3 měsíce (6 u vedoucích pracovníků) podle ZP.', null=True, verbose_name='Zkušební doba (v měsících)'),
        ),
    ]
