# Generated by Django 6.0.2 on 2026-02-10 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_pozice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osobnidotaznik',
            name='pozice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dotazniky', to='onboarding.pozice', verbose_name='Pozice'),
        ),
    ]
