# Generated by Django 6.0.2 on 2026-02-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_osobnidotaznik_nastup_datum_osobnidotaznik_pomer_do_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osobnidotaznik',
            name='smlouva_pracovni_pomer',
            field=models.FileField(blank=True, null=True, upload_to='smlouvy/', verbose_name='Pracovní smlouva (DOCX)'),
        ),
    ]
