# Generated by Django 6.0.2 on 2026-02-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_osobnidotaznik_smlouva_pracovni_pomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='osobnidotaznik',
            name='smlouva_pracovni_pomer_pdf',
            field=models.FileField(blank=True, null=True, upload_to='smlouvy/pdf', verbose_name='Pracovní smlouva (PDF)'),
        ),
    ]
